name: Deploy to GitHub Pages

# Ejecutar el flujo en push o pull_request a la rama main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Descargar el repositorio
      - name: Check out the repo
        uses: actions/checkout@v3

      # 2. Instalar Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Generar el build de producción
      - name: Build
        run: npm run build

      # 5. Subir los archivos generados en ./dist como un artifact
      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 1. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          # La rama gh-pages se creará automáticamente para alojar tu sitio
          branch: gh-pages
